In [1]:
import sys

sys.path.append("..")
from FIA.FIA import *
from helpers.normalization import *

In [2]:
data = pd.read_csv("/mnt/d/runs/FIA/Com20_single/merged/data_matrix.tsv", sep="\t")

In [3]:
data

,mz,mGAM,mGAM.1,mGAM.2,mGAM.3,mGAM.4,mGAM.5,NT5001,NT5001.1,NT5001.2,...,NT5076.2,NT5076.3,NT5076.4,NT5076.5,TH,TH.1,TH.2,TH.3,TH.4,TH.5
0,50.001,36743.0,20193.0,38552.0,22564.0,33739.0,21017.0,17933.0,16542.0,20699.0,...,15101.0,16240.0,17380.0,15788.0,15863.0,11965.0,21841.0,10745.0,17427.0,11356.0
1,50.003,27199.0,16975.0,30837.0,16656.0,31688.0,12880.0,15227.0,11838.0,18970.0,...,14207.0,12485.0,16015.0,18716.0,17005.0,9186.0,18211.0,9506.0,20396.0,9877.0
2,50.005,34332.0,22372.0,41795.0,25102.0,35968.0,19017.0,20611.0,16192.0,24241.0,...,9440.0,17805.0,10727.0,12871.0,22486.0,10663.0,27174.0,13789.0,24232.0,10973.0
3,50.007,34059.0,22456.0,41958.0,22528.0,34062.0,22580.0,18963.0,16895.0,23322.0,...,14235.0,15643.0,12680.0,17039.0,20730.0,10431.0,24107.0,12782.0,24906.0,12600.0
4,50.009,27834.0,16415.0,30820.0,16099.0,27299.0,15702.0,13981.0,12729.0,18988.0,...,10034.0,8819.0,10421.0,12843.0,14880.0,6935.0,19285.0,8658.0,17989.0,8301.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824995,1699.991,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
824996,1699.993,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
824997,1699.995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
824998,1699.997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
824999,1699.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
data.iloc[:,1]

0         36743.0
1         27199.0
2         34332.0
3         34059.0
4         27834.0
           ...
824995        0.0
824996        0.0
824997        0.0
824998        0.0
824999        0.0
Name: mGAM, Length: 825000, dtype: float64

In [19]:
def spectral_entropy(spectrum):
    return -np.sum(spectrum * np.where(spectrum != 0, np.log(spectrum), 0))

def spectra_entropy_divergence(spec1, spec2):
    return ( 2 * spectral_entropy(total_ion_count_normalization(spec1 + spec2)) -
             spectral_entropy(total_ion_count_normalization(spec1)) - spectral_entropy(total_ion_count_normalization(spec2)) 
            ) / np.log(4)

In [29]:
spectra_entropy_divergence(spec1=data.iloc[:,1], spec2=data.iloc[:,-1])

0.24852884382480706

In [18]:
total_ion_count_normalization(data.iloc[:,1]) * np.where(total_ion_count_normalization(data.iloc[:,1]) != 0, np.log(total_ion_count_normalization(data.iloc[:,1])), 0)

0        -0.000017
1        -0.000013
2        -0.000016
3        -0.000016
4        -0.000013
            ...
824995    0.000000
824996    0.000000
824997    0.000000
824998    0.000000
824999    0.000000
Name: mGAM, Length: 825000, dtype: float64